- name: provision aws resources and deploy lambda function
  hosts: localhost
  vars:
    - jar_path: ../target/scala-2.11
    - jar_name: telemetry-parquet-converter.jar

  tasks:
    - name: create jar
      command: sbt assembly chdir=../

    - name: upload jar
      # s3 module fails, use aws cli
      command: aws s3 cp {{jar_path}}/{{jar_name}} s3://{{function_bucket}}/{{jar_name}}

    - name: launch cloudformation
      cloudformation:
        stack_name: "telemetry-lambda-parquet"
        state: "present"
        region: "{{region}}"
        disable_rollback: true
        template: "files/cloudformation.json"
        template_parameters:
          Account: "{{account}}"
          FunctionBucket: "{{function_bucket}}"
          ScalaJar: "{{jar_name}}"
        tags:
          type: "telemetry"
          application: "parquet-converter"
      register: cloudformation